services:
  audiobookshelf-sonos:
    container_name: audiobookshelf-sonos
    image: audiobookshelf-sonos
    volumes:
      - "./config.js:/app/config.js"
      - "./server.js:/app/server.js"
      - "./sonos-service.js:/app/sonos-service.js"
      - "./sonos.wsdl:/app/sonos.wsdl"
      - "./test.wsdl:/app/test.wsdl"
      - "./utils.js:/app/utils.js"
    ports:
      - 3333:80
